- name: Install Gradle 8.4 (System)
  run: |
    wget https://services.gradle.org/distributions/gradle-8.4-bin.zip
    unzip gradle-8.4-bin.zip
    sudo mv gradle-8.4 /opt/gradle
    echo "/opt/gradle/bin" >> $GITHUB_PATH
